#%RAML 1.0 DataType
type: object
properties:  
  status:
    type: string
    example: "Match Found"
  latitude:
    type: string
    example: "26.41970153"
  longitude:
    type: string
    example: "-81.72341242"



